### ISSUE TITLE
Link to this git repo from MetaCPAN

### ISSUE THREAD

**Issue by szabgab** [Htbaa/Validation-Class#2]
Unlike https://metacpan.org/dist/WebService-Rackspace-CloudFiles  this distribution https://metacpan.org/dist/Validation-Class does not have this information in its META.* files. (and both have only `META.yml` and not the newer `META.json`.

Dist::Zilla has several ways to include this information. [this article](https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions) includes one of them.

**Comment by Htbaa** [comment]
Hi @szabgab, thanks for mentioning this to me and providing a link on how to do this. I've added it to the `dist.ini`. This should suffice right?

**Comment by szabgab** [comment]
I hope. We'll see once you release a new version to CPAN
